[versions]
lavalink-api = "4.1.1"
lavalink-server = "4.1.1"
lavaplayer = "2.2.4"
httpclient5 = "5.5.1"
httpcore5 = "5.3.6"

[plugins]
lavalink = { id = "dev.arbjerg.lavalink.gradle-plugin", version = "1.1.2" }

[libraries]
lavaplayer = { group = "dev.arbjerg", name = "lavaplayer", version.ref = "lavaplayer" }
httpclient5 = { group = "org.apache.httpcomponents.client5", name = "httpclient5", version.ref = "httpclient5" }
httpcore5 = { group = "org.apache.httpcomponents.core5", name = "httpcore5", version.ref = "httpcore5" }
